// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------------- //
// read_rising_edge //
// ---------------- //

#define read_rising_edge_wrap_target 3
#define read_rising_edge_wrap 3
#define read_rising_edge_pio_version 1

static const uint16_t read_rising_edge_program_instructions[] = {
    0x00c0, //  0: jmp    pin, 0
    0x00c3, //  1: jmp    pin, 3
    0x0000, //  2: jmp    0
            //     .wrap_target
    0x4010, //  3: in     pins, 16
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program read_rising_edge_program = {
    .instructions = read_rising_edge_program_instructions,
    .length = 4,
    .origin = -1,
    .pio_version = read_rising_edge_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config read_rising_edge_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + read_rising_edge_wrap_target, offset + read_rising_edge_wrap);
    return c;
}
#endif

