#ifndef TUSB_CONFIG_H_
#define TUSB_CONFIG_H_

#define CFG_TUSB_MCU OPT_MCU_RP2040

#define CFG_TUD_ENABLED 1
#define CFG_TUD_VENDOR 1

#define CFG_TUD_VENDOR_RX_BUFSIZE 64
#define CFG_TUD_VENDOR_TX_BUFSIZE 64

#define BOARD_TUD_MAX_SPEED OPT_MODE_FULL_SPEED
#define CFG_TUD_MAX_SPEED BOARD_TUD_MAX_SPEED
#define CFG_TUSB_RHPORT0_MODE (OPT_MODE_DEVICE | BOARD_TUD_MAX_SPEED)

#endif /* TUSB_CONFIG_H_ */
